### ISSUE TITLE
Reporter error in judoscale-delayed_job when log level is set

### ISSUE THREAD

**Issue by alexmdavis** [judoscale/judoscale-ruby#143]
Rails 4.2.11.3. Occurs when log level is set via config file or ENV variable, for both `:warn` and `:info`. (Also occurs for gem version 1.2.3).

```
[Judoscale] Reporter error: #<NoMethodError: undefined method `reopen' for nil:NilClass>
[Judoscale] /app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-63ea815f1155/activesupport/lib/active_support/core_ext/kernel/reporting.rb:106:in `ensure in capture'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-63ea815f1155/activesupport/lib/active_support/core_ext/kernel/reporting.rb:106:in `capture'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/job_metrics_collector/active_record_helper.rb:19:in `run_silently'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/job_metrics_collector/active_record_helper.rb:26:in `select_rows_silently'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-delayed_job-1.3.0/lib/judoscale/delayed_job/metrics_collector.rb:37:in `collect'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:60:in `block (2 levels) in run_metrics_collection'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:92:in `log_exceptions'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:60:in `block in run_metrics_collection'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:59:in `each'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:59:in `flat_map'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:59:in `run_metrics_collection'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:49:in `block (2 levels) in run_loop'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:48:in `loop'
[Judoscale] /app/vendor/bundle/ruby/2.7.0/gems/judoscale-ruby-1.3.0/lib/judoscale/reporter.rb:48:in `block in run_loop'
```

**Comment by adamlogic** [comment]
Hey Alex, thanks for the report! I'll try to repro this on my end.

**Comment by adamlogic** [comment]
I'm having all sorts of issues getting things running locally with Rails 4.2.11.3, so I can't reproduce this exact issue, but it looks like there are some [documented](https://stackoverflow.com/questions/30445255/now-that-activerecordbase-silence-is-gone-how-do-i-bring-back-that-functio) [issues](https://github.com/rails/sprockets-rails/issues/422) with `logger.silence` in Rails 4.

The only real workaround I would recommend is this monkey patch that removes the call to `logger.silence` from our [`run_silently` helper](https://github.com/judoscale/judoscale-ruby/blob/main/judoscale-ruby/lib/judoscale/job_metrics_collector/active_record_helper.rb#L17-L23):

```ruby
class Judoscale::DelayedJob::MetricsCollector
  def run_silently(&block)
    yield
  end
end
```

**Comment by alexmdavis** [comment]
Thanks for taking a look.
